apiVersion: apps/v1
kind: Deployment
metadata:
  name: grade
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grade
  template:
    metadata:
      labels:
        app: grade
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: grade
          image: devopszms2024/zms-devops-grade-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8086
          envFrom:
            - configMapRef:
                name: grade-configmap
            - configMapRef:
                name: mongodb-grade-configmap
            - secretRef:
                name: mongodb-grade-secret
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "my-kafka.backend.svc.cluster.local:9092"
            - name: KAFKA_AUTH_PASSWORD
              value: "iiL8apGJ9c"
---
apiVersion: v1
kind: Service
metadata:
  name: grade
  namespace: backend
spec:
  selector:
    app: grade
  ports:
    - protocol: TCP
      name: http
      port: 8086
      targetPort: 8086
    - protocol: TCP
      name: grpc
      port: 8001
      targetPort: 8001
